apiVersion: v1
kind: ConfigMap

metadata:
  name: chalet-core-config

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://chalet-core-mysql-service:{{ .Values.mysql.service.port }}/{{ .Values.mysql.database }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.username | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profile | quote }}
