apiVersion: apps/v1
kind: Deployment

metadata:
  name: chalet-core-mysql-deployment

spec:
  replicas: {{ .Values.mysql.replicaCount }}

  selector:
    matchLabels:
      app: chalet-core-mysql

  template:
    metadata:
      labels:
        app: chalet-core-mysql

    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chalet-core.mysqlSecretName" . }}
                  key: {{ .Values.mysql.auth.rootPasswordKey }}

            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}

            - name: MYSQL_USER
              value: {{ .Values.mysql.username | quote }}

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chalet-core.mysqlAppSecretName" . }}
                  key: {{ .Values.mysql.auth.appPasswordKey }}

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h localhost -uroot -p"$MYSQL_ROOT_PASSWORD" --silent

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h localhost -uroot -p"$MYSQL_ROOT_PASSWORD" --silent

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h localhost -uroot -p"$MYSQL_ROOT_PASSWORD" --silent

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: chalet-core-mysql-pvc
