{{- if not .Values.mysql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chalet-core.mysqlSecretName" . }}
type: Opaque
stringData:
  {{ .Values.mysql.auth.rootPasswordKey }}: {{ required "mysql.auth.rootPassword is required when mysql.auth.existingSecret is not set" .Values.mysql.auth.rootPassword | quote }}
{{- end }}
