replicaCount: 1

image:
  repository: 712532372065.dkr.ecr.ap-south-1.amazonaws.com/chalet-core
  tag: "1.0.6"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

mysql:
  replicaCount: 1
  image: mysql:8.4

  service:
    type: ClusterIP
    port: 3306

  database: chalet_db
  username: root

  auth:
    existingSecret: ""
    rootPassword: ""
    rootPasswordKey: mysql-root-password

  storage: 2Gi

spring:
  profile: default
